// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFStudentAccomodation.Models
{
    [Table("Appartment")]
    public partial class Appartment
    {
        public Appartment()
        {
            Rooms = new HashSet<Room>();
        }

        [Key]
        public int AppartNo { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(1)]
        public string Types { get; set; }

        [InverseProperty(nameof(Room.AppartNoNavigation))]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}