// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFStudentAccomodation.Models
{
    [Table("Dormitory")]
    public partial class Dormitory
    {
        public Dormitory()
        {
            Rooms = new HashSet<Room>();
        }

        [Key]
        public int DormitoryNo { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }

        [InverseProperty(nameof(Room.DormitoryNoNavigation))]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}