// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EFStudentAccomodation.Models
{
    public partial class EfstudentaccommodationdbContext : DbContext
    {
        public EfstudentaccommodationdbContext()
        {
        }

        public EfstudentaccommodationdbContext(DbContextOptions<EfstudentaccommodationdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Appartment> Appartments { get; set; }
        public virtual DbSet<Dormitory> Dormitories { get; set; }
        public virtual DbSet<Leasing> Leasings { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Appartment>(entity =>
            {
                entity.HasKey(e => e.AppartNo)
                    .HasName("PK__Appartme__7AB018ABF51BC03C");

                entity.Property(e => e.AppartNo).ValueGeneratedNever();

                entity.Property(e => e.Address).IsUnicode(false);

                entity.Property(e => e.Types)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('3')")
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<Dormitory>(entity =>
            {
                entity.HasKey(e => e.DormitoryNo)
                    .HasName("PK__Dormitor__14187F84AF1EB2BC");

                entity.Property(e => e.DormitoryNo).ValueGeneratedNever();

                entity.Property(e => e.Address).IsUnicode(false);

                entity.Property(e => e.Name).IsUnicode(false);
            });

            modelBuilder.Entity<Leasing>(entity =>
            {
                entity.HasKey(e => e.LeasingNo)
                    .HasName("PK__tmp_ms_x__F28F0D7FF301A060");

                entity.HasOne(d => d.PlaceNoNavigation)
                    .WithMany(p => p.Leasings)
                    .HasForeignKey(d => d.PlaceNo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Leasing_Room");

                entity.HasOne(d => d.UserNoNavigation)
                    .WithMany(p => p.Leasings)
                    .HasForeignKey(d => d.UserNo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Leasing_Student");
            });

            modelBuilder.Entity<Message>(entity =>
            {
                entity.HasKey(e => e.MessageNo)
                    .HasName("PK__Message__C87CFBFC3BE27BC8");

                entity.Property(e => e.Body).IsUnicode(false);

                entity.Property(e => e.Receiver).IsUnicode(false);

                entity.Property(e => e.Sender).IsUnicode(false);

                entity.HasOne(d => d.UserNoNavigation)
                    .WithMany(p => p.Messages)
                    .HasForeignKey(d => d.UserNo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Message_User");
            });

            modelBuilder.Entity<Room>(entity =>
            {
                entity.HasKey(e => e.PlaceNo)
                    .HasName("PK__Room__D522626EC87EA547");

                entity.Property(e => e.PlaceNo).ValueGeneratedNever();

                entity.HasOne(d => d.AppartNoNavigation)
                    .WithMany(p => p.Rooms)
                    .HasForeignKey(d => d.AppartNo)
                    .HasConstraintName("FK_Room_Appartment");

                entity.HasOne(d => d.DormitoryNoNavigation)
                    .WithMany(p => p.Rooms)
                    .HasForeignKey(d => d.DormitoryNo)
                    .HasConstraintName("FK_Room_Dormitory");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.UserNo)
                    .HasName("PK__User__178895BF48BE92C8");

                entity.Property(e => e.UserNo).ValueGeneratedNever();

                entity.Property(e => e.Name).IsUnicode(false);

                entity.Property(e => e.Password).IsUnicode(false);

                entity.Property(e => e.Role).IsUnicode(false);

                entity.Property(e => e.Username).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}