// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFStudentAccomodation.Models
{
    [Table("Leasing")]
    public partial class Leasing
    {
        [Key]
        public int LeasingNo { get; set; }
        public int UserNo { get; set; }
        public int PlaceNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTo { get; set; }

        [ForeignKey(nameof(PlaceNo))]
        [InverseProperty(nameof(Room.Leasings))]
        public virtual Room PlaceNoNavigation { get; set; }
        [ForeignKey(nameof(UserNo))]
        [InverseProperty(nameof(User.Leasings))]
        public virtual User UserNoNavigation { get; set; }
    }
}