// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFStudentAccomodation.Models
{
    [Table("Message")]
    public partial class Message
    {
        [Key]
        public int MessageNo { get; set; }
        public int UserNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Required]
        [StringLength(50)]
        public string Body { get; set; }
        [Required]
        [StringLength(50)]
        public string Sender { get; set; }
        [Required]
        [StringLength(50)]
        public string Receiver { get; set; }

        [ForeignKey(nameof(UserNo))]
        [InverseProperty(nameof(User.Messages))]
        public virtual User UserNoNavigation { get; set; }
    }
}