// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFStudentAccomodation.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Leasings = new HashSet<Leasing>();
            Messages = new HashSet<Message>();
        }

        [Key]
        [Column("UserNO")]
        public int UserNo { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [StringLength(50)]
        public string Password { get; set; }
        [Required]
        [StringLength(50)]
        public string Role { get; set; }
        public bool? HasRoom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RegistrationDate { get; set; }
        public int? Age { get; set; }

        [InverseProperty(nameof(Leasing.UserNoNavigation))]
        public virtual ICollection<Leasing> Leasings { get; set; }
        [InverseProperty(nameof(Message.UserNoNavigation))]
        public virtual ICollection<Message> Messages { get; set; }
    }
}